import { db } from '/firebase';
import { collection, addDoc, getDoc, getDocs, deleteDoc, doc, query, where } from 'firebase/firestore';

async function addCard(card) {
    const docRef = await addDoc(collection(db, 'Cards'), {
        front: card.front,
        back: card.back,
        edittable: card.edittable,
        key: card.key
    });
    return docRef.id;
}
//this function needs document autogenerated id to be passed in, so is unusable at the moment
async function getCard(cardId) {
    const cardSnapshot = await getDoc(doc(db, 'Cards', cardId));
    return cardSnapshot.data();
}
//workaround for getting a card by key
async function getaCard(key) {
    const q = query(collection(db, 'Cards'), where('key', '==', key));
    const querySnapshot = await getDocs(q);
    return querySnapshot.docs[0].data();
}

async function getCards() {
    const cardSnapshot = await getDocs(collection(db, 'Cards'));
    return cardSnapshot.docs.map((doc) => doc.data());
}
//very inefficient, need to find a better way to delete a document
async function deleteCard(key) {
    const q = query(collection(db, 'Cards'), where('key', '==', key));
    const querySnapshot = await getDocs(q);
    await deleteDoc(querySnapshot.docs[0].ref);
}

export { addCard, getCards, getaCard, deleteCard };
